### ISSUE TITLE
Missing intermediate confirmation step

### ISSUE THREAD

**Issue by lehmansarahm** [likhongomes/Smart-Prompter-iOS#14]
In the task completion pipeline, there is a screen / slider for user to indicate that they are on their way.  There is no intermediate confirmation step after that to confirm that they are ready to take a picture.  Screenshot of Android app attached for clarification.

![2 - Completion Screen](https://user-images.githubusercontent.com/20825431/73669182-09ef0a00-4675-11ea-96aa-23ca0bd15d16.png)

**Comment by likhongomes** [comment]
done
