### ISSUE TITLE
Missing task completion confirmation / reward screen

### ISSUE THREAD

**Issue by lehmansarahm** [likhongomes/Smart-Prompter-iOS#15]
There is no clear "completion confirmation" or "reward" screen to indicate to the user that they have successfully completed all steps for this alarm.  In the Android version, there is either a progress "wheel" (reflecting the percentage of tasks completed for that day) or a high-fiving dog (when all tasks for today have been completed).  The user is then presented with a button to return them to the main list screen.  Screenshots attached for clarification.

![4 - Confirmation Screen](https://user-images.githubusercontent.com/20825431/73669395-5c302b00-4675-11ea-9230-2d6226aba9da.png)

<img width="414" alt="Screen Shot 2020-02-03 at 11 06 07 AM" src="https://user-images.githubusercontent.com/20825431/73669409-62260c00-4675-11ea-99ec-c72223eb064e.png">

**Comment by likhongomes** [comment]
resolved
