### ISSUE TITLE
Completed alarm records missing accountability info

### ISSUE THREAD

**Issue by lehmansarahm** [likhongomes/Smart-Prompter-iOS#20]
Admin app screen that displays info for completed alarms should include the following:

- Date / time of the original alarm
- Date / time alarm was acknowledged
- Date / time alarm was completed
- Picture user took + picture file path

**Comment by lehmansarahm** [comment]
Refer to Issue #18 for acknowledgment / completion state transitions.  All data should be read-only, so you can use labels instead of text boxes if that makes things easier and saves space...

**Comment by likhongomes** [comment]
resolved
