### ISSUE TITLE
Current UI layout no good on "forehead-less" phones

### ISSUE THREAD

**Issue by lehmansarahm** [likhongomes/Smart-Prompter-iOS#30]
Tania and Katherine both have iPhone 10s, which do not have a forehead (screen goes all the way to phone bezel).  This makes buttons that are really close to the edge (especially top edge) very finicky to interact with.

Test app on iPhone 10 emulator, move buttons away from edge or make them MUCH bigger

**Comment by lehmansarahm** [comment]
Also, please update any alarm editing screens in the Admin app to have "Reset" button text, instead of "Cancel"

**Comment by likhongomes** [comment]
so, for the reset button, the data is actually not changed until the user clicks done, so I guess that's what you mean by the reset button (to be able to undo any changes you made). But if you want to reset back to original process after done button has been pressed, then I will have to change the data structure. So for now I will just rename the Cancel button to Reset
